package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"text/template"
)

var (
	generate = flag.Bool("generate", false, "Generate structs")
)

func main() {
	flag.Parse()

	if *generate {
		generator()
		return
	}

	fmt.Println("Nothing to do")
}

const genFolder = "./gen/"

func generator() {
	if _, err := os.Open(genFolder + "models.go"); err == nil {
		rmcmd := exec.Command("rm", genFolder+"models.go")
		rmcmd.Run()
	}

	f, err := os.Create("contributors.go")
	die(err)
	defer f.Close()
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package gen


`))
